#SERVER
server.local=true
server.test=false
server.daoautoupdater=false
server.sv=1
server.name=Local
server.ip=127.0.0.1
server.port=14445
# server.sv1=NroLight:fw.patus.tech:14449:0,0,0
server.waitlogin=3
server.maxperip=999
server.maxplayer=1000
server.expserver=3

#DATABASE
database.driver=com.mysql.jdbc.Driver
database.host=127.0.0.1
database.port=3306
database.name=team2026
database.user=root
database.pass=
database.min=1
database.max=1
database.lifetime=120000
