#SERVER
server.local=true
server.test=false
server.daoautoupdater=false
server.sv=${SERVER_SV}
server.name=${SERVER_NAME}
server.ip=${SERVER_IP}
server.port=${SERVER_PORT}
server.waitlogin=${SERVER_WAITLOGIN}
server.maxperip=${SERVER_MAXPERIP}
server.maxplayer=${SERVER_MAXPLAYER}
server.expserver=${SERVER_EXPSERVER}

#DATABASE
database.driver=com.mysql.jdbc.Driver
database.host=${DB_HOST}
database.port=${DB_PORT}
database.name=${DB_NAME}
database.user=${DB_USER}
database.pass=${DB_PASSWORD}
database.min=${DB_MIN}
database.max=${DB_MAX}
database.lifetime=${DB_LIFETIME}
